menu(MaxCals, MaxPre, TCals, TPre, DE, AL, CE, ND, BId, BNom, BCals, BSa, BPre, BCat, BTemp, BBas,
     PrID, PrNom, PrCals, PrSa, PrPre, PrOri, PrTex, PrCoc,
     G1ID, G1Nom, G1Cals, G1Sa, G1Pre, G1Cat, G1Tam, G1Coc,
     G2ID, G2Nom, G2Cals, G2Sa, G2Pre, G2Cat, G2Tam, G2Coc,
     G3ID, G3Nom, G3Cals, G3Sa, G3Pre, G3Cat, G3Tam, G3Coc,
     PoID, PoNom, PoCals, PoSa, PoPre, PoTex, PoTemp) :-
    bebida(BId, BNom, BCals, ND, BSa, BPre, DE, AL, CE, BCat, BTemp, BBas),
    proteina(PrID, PrNom, PrCals, ND, PrSa, PrPre, DE, AL, CE, PrOri, PrTex, PrCoc),
    guarnicion(G1ID, G1Nom, G1Cals, ND, G1Sa, G1Pre, DE, AL, CE, G1Cat, G1Tam, G1Coc),
    guarnicion(G2ID, G2Nom, G2Cals, ND, G2Sa, G2Pre, DE, AL, CE, G2Cat, G2Tam, G2Coc),
    guarnicion(G3ID, G3Nom, G3Cals, ND, G3Sa, G3Pre, DE, AL, CE, G3Cat, G3Tam, G3Coc),
    G2ID \= G1ID,
    G3ID \= G1ID,
    G3ID \= G2ID,
    postre(PoID, PoNom, PoCals, ND, PoSa, PoPre, DE, AL, CE, PoTex, PoTemp),
    TCals is BCals + PrCals + G1Cals + G2Cals + G3Cals + PoCals,
    TCals =< MaxCals,
    TPre is BPre + PrPre + G1Pre + G2Pre + G3Pre + PoPre,
    TPre =< MaxPre.
